spring:
  application:
    name: springcloud-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
# nacos 默认没有用户名和密码
#      username: nacos
#      password: nacos
logging:
  level:
    root: error
